language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  matrix:
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
install:
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - pip install coveralls --use-mirrors
  - python setup.py install
script: coverage run --omit *site-packages*,*tests* runtests.py
after_success:
  - coveralls
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.3
    - python: "3.3"
      env: DJANGO_VERSION=1.4
